
# Post  http://localhost:5000/user/

# Content-Type: application/json;

# {
#     "firstName":"yasira"
# }

Post http://localhost:5000/user/

Content-Type: application/json;

{
  "firstName":"yasira",
  "lastName":"bance",
   "otherName":"faiza",
  "email":"yasirat@gmail.com",
    "password":"12345"
}